# Generated by Django 4.1.4 on 2022-12-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[(1, ' staff'), (2, ' doctor'), (3, ' nurse'), (4, 'manager'), (5, 'admin')], default=5, max_length=50),
        ),
    ]
