# Generated by Django 4.1.4 on 2022-12-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_role_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='roles',
        ),
    ]
